name: Build and test

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
